name: Add or Update Summary File

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Markdown file path (e.g., summaries/chatgpt-summary.md)'
        required: true
      content:
        description: 'Content to write into the file'
        required: true

jobs:
  update-summary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or update markdown file
        run: |
          mkdir -p "$(dirname "${{ inputs.filename }}")"
          echo "${{ inputs.content }}" > "${{ inputs.filename }}"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "${{ inputs.filename }}"
          git commit -m "Add/update summary: ${{ inputs.filename }}"
          git push
